Repository Sports-day/sports-day-admin, pull requests merged in 2024-10, with the labels that each got.

#68 スナックバー追加しましたよ
  components/league/legacy/GameForm.tsx
  components/match/matchEditor.tsx
Labels: Problem: bug, Type: design

#69 NextJSのビルドテストを追加しました
  .github/workflows/docker-publish.yml
  .github/workflows/nextjs-build.yml
Labels: Type: improvement

#70 リンク修正など Feature/fix link
  components/automation/AutomaticMatchEditor.tsx
  components/automation/AutomaticMatchEditorForImizu.tsx
  components/automation/CrossGameAutomaticMatchEditor.tsx
  components/automation/makeLeagueMatches.tsx
  components/images/imageEditor.tsx
  components/information/informationList.tsx
  components/layout/navPrivacyPolicyDrawer.tsx
  components/layout/privacyPolicy.tsx
  components/match/matchCard.tsx
  components/match/matchEditor.tsx
  components/sports/sportCreator.tsx
  components/sports/sportEditor.tsx
  components/theme/colorModeProvider.tsx
  src/lib/ApiClient.ts
Labels: Problem: bug, Type: improvement
