Repository Sports-day/sports-day-admin, pull requests merged in 2024-05, with the labels that each got.

#27 チームエクスポート機能の実装
  app/(authenticated)/teams/export/page.tsx
  app/(authenticated)/teams/page.tsx
  components/teams/export/exportTeams.tsx
  components/teams/teamsTable.tsx
  package.json
  yarn.lock
Labels: Priority: high, Type: new feature

#29 TeamTagにsportIdを追加
  src/models/TeamTagModel.ts
Labels: Type: improvement

#30 チームの情報を表示する画面の実装
  app/(authenticated)/teams/[id]/page.tsx
  components/teams/teamEditor.tsx
  components/teams/teamsTable.tsx
Labels: Type: new feature

#31 リーグ編成画面 Feature/#21 league
  app/(authenticated)/league/[id]/page.tsx
  app/(authenticated)/league/page.tsx
  app/(authenticated)/loading.tsx
  app/(authenticated)/locations/page.tsx
  app/(authenticated)/page.tsx
  app/(authenticated)/sports/[id]/page.tsx
  app/(authenticated)/sports/create/page.tsx
  app/(authenticated)/sports/page.tsx
  app/(authenticated)/users/csv/page.tsx
  app/error.tsx
  app/not-found.tsx
  components/auth/LogoutButton.tsx
  components/layout/buttonLarge.tsx
  components/layout/cardBackground.tsx
  components/layout/navigation.tsx
  components/league/dndContainer.tsx
  components/league/dndItem.tsx
  components/league/dndSortableItem.tsx
  components/league/leagueDnd.tsx
  components/league/leagueSportsList.tsx
  components/sports/leagueList.tsx
  components/sports/sportCreator.tsx
  components/sports/sportEditor.tsx
  components/sports/sportInfoField.tsx
  components/sports/sportsList.tsx
  components/theme/theme.tsx
  package.json
  yarn.lock
Labels: Type: new feature

#34 teamを削除する機能の実装
  components/teams/teamDelete.tsx
  components/teams/teamEditor.tsx
Labels: Type: new feature

#37 試合結果入力画面　Feature/#32 match result
  app/(authenticated)/league/page.tsx
  app/(authenticated)/locations/page.tsx
  app/(authenticated)/page.tsx
  app/(authenticated)/sports/[id]/[gameId]/[matchId]/page.tsx
  app/(authenticated)/sports/[id]/[gameId]/page.tsx
  app/(authenticated)/sports/[id]/league/page.tsx
  app/(authenticated)/sports/[id]/page.tsx
  app/(authenticated)/sports/[id]/tournament/page.tsx
  app/(authenticated)/tournament/page.tsx
  components/layout/navigation.tsx
  components/league/leagueSportsList.tsx
  components/match/matchEditor.tsx
  components/sports/leagueList.tsx
  components/sports/sportEditor.tsx
Labels: Type: new feature

#38 ゲーム配下のルーティングを一部修正
  app/(authenticated)/sports/[id]/create-league/page.tsx
  app/(authenticated)/sports/[id]/create-tournament/page.tsx
  app/(authenticated)/sports/[id]/games/[gameId]/matches/[matchId]/page.tsx
  app/(authenticated)/sports/[id]/games/[gameId]/page.tsx
  app/(authenticated)/sports/[id]/page.tsx
  components/sports/leagueList.tsx
  middleware.ts
Labels: Type: improvement

#39 リーグ表のプロトタイプ
  app/(authenticated)/sports/[id]/create-league/page.tsx
  app/(authenticated)/sports/[id]/games/[gameId]/page.tsx
  components/league/create/dndContainer.tsx
  components/league/create/dndItem.tsx
  components/league/create/dndPlaceHolder.tsx
  components/league/create/dndSortableItem.tsx
  components/league/create/leagueDnd.tsx
  components/league/table/leagueTable.tsx
  components/league/table/matchCell.tsx
  components/league/table/slashCell.tsx
  components/league/table/teamCell.tsx
Labels: Type: new feature

#40 試合に関するコンポーネントの修正と一覧表示コンポーネントの作成
  app/(authenticated)/page.tsx
  app/(authenticated)/sports/[id]/games/[gameId]/page.tsx
  app/(authenticated)/sports/[id]/page.tsx
  components/match/inProgressMatchList.tsx
  components/match/matchCard.tsx
  components/match/matchEditor.tsx
  components/match/matchList.tsx
  components/match/sportInProgressMatchList.tsx
  src/models/MatchModel.ts
Labels: Type: improvement, Type: new feature

#41 タグに関する機能
  app/(authenticated)/tags/[id]/page.tsx
  app/(authenticated)/tags/create/page.tsx
  app/(authenticated)/tags/page.tsx
  components/layout/navigation.tsx
  components/tags/tagCreator.tsx
  components/tags/tagEditor.tsx
  components/tags/tagsAgGrid.tsx
Labels: Type: new feature

#44 チームメンバー編集機能の実装
  app/(authenticated)/teams/[id]/page.tsx
  components/teams/addTeamMemberDialog.tsx
  components/teams/teamEditor.tsx
Labels: Type: new feature

#45 リーグの試合を生成する機能
  app/(authenticated)/sports/[id]/games/[gameId]/generate-league-matches/page.tsx
  app/(authenticated)/sports/[id]/games/[gameId]/page.tsx
  components/automation/makeLeagueMatches.tsx
Labels: Type: new feature

#48 リーグ編成およびリーグ作成機能
  app/(authenticated)/sports/[id]/create-league/page.tsx
  app/(authenticated)/sports/[id]/games/[gameId]/page.tsx
  app/(authenticated)/sports/[id]/page.tsx
  components/league/legacy/AddGameEntryDialog.tsx
  components/league/legacy/ConfirmDialog.tsx
  components/league/legacy/GameEditFields.tsx
  components/league/legacy/GameEntryContent.tsx
  components/league/legacy/GameEntryList.tsx
  components/league/legacy/GameForm.tsx
  components/match/inProgressMatchList.tsx
  components/match/sportInProgressMatchList.tsx
Labels: Problem: bug, Type: new feature

#49 エントリー機能の便利機能
  app/(authenticated)/sports/[id]/games/[gameId]/page.tsx
  components/league/legacy/AddGameEntryAutomation.tsx
Labels: Type: new feature

#50 別のリーグにエントリーしているの審判が見えない不具合
  components/match/matchEditor.tsx
Labels: Problem: bug

#51 試合時間を変更できる機能の実装
  components/match/matchEditor.tsx
Labels: Type: new feature

#52 審判がない試合の追加
  components/automation/AutomaticMatchEditor.tsx
  components/automation/CrossGameAutomaticMatchEditor.tsx
Labels: Type: new feature

#53 Feature/refactor style
  components/league/table/leagueTable.tsx
  components/match/matchList.tsx
Labels: Type: improvement

#54 画像アップロード機能 Feature/#25 image upload feature
  app/(authenticated)/images/[id]/page.tsx
  app/(authenticated)/images/create/page.tsx
  app/(authenticated)/images/page.tsx
  components/images/imageCreator.tsx
  components/images/imageEditor.tsx
  components/layout/buttonLarge.tsx
  components/layout/navigation.tsx
  components/sports/leagueList.tsx
  components/sports/sportEditor.tsx
  components/sports/sportsList.tsx
  yarn.lock
Labels: Type: new feature

#55 リーグの結果表示
  components/league/table/leagueTable.tsx
  components/league/table/textCell.tsx
Labels: Type: improvement, Type: new feature
